baseURL: 'https://qurist.github.io/'
languageCode: 'en-us'
title: 'Aniruddha Bapat'
theme: 'PaperMod'

menu:
  main:
    - name: Curriculum Vitae
      url: curriculum-vitae/
      weight: 1  
    - name: Papers
      url: papers/
      weight: 2
      
params:
  # label:
  #   text: "Aniruddha Bapat"
  #   icon: /favicon.ico
  #   iconHeight: 24

  math: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  hideFooter: True
  ShowToc: true

  assets:
    disableHLJS: true
    disableScrollBarStyle: true

  cover:
    hiddenInList: true
    hiddenInSingle: true

  profileMode:
    enabled: true
    title: Aniruddha Bapat
    subtitle: I am a physicist who has worked primarily in the field of quantum computation, 
        in addition to about a year's worth of work each in computational biophysics and quantitative finance. 
        I have a broad and ever evolving range of interests, both professionally and personally.   

        Until January 2024, I was a researcher at the high-frequency trading firm Optiver. 
        Before that, I worked as a postdoc in quantum computing at the [Lawrence Berkeley National Laboratory](http://www.lbl.gov "lbl.gov"). 
        You can find out more in my [CV](curriculum-vitae/), or read more about me here.
    imageUrl: "/profile_pic_2024.jpeg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Aniruddha Bapat

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/qurist"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/aniruddhabapat/"
    - name: "googlescholar"
      url: "https://scholar.google.com/citations?user=D5qEcgYAAAAJ&hl=en"
    - name: "email"
      url: "mailto:ani1729@gmail.com"
    - name: "CV"
      url: "/cv_aniruddhabapat.pdf"

  cvItems: 
    - name: "work-experience"
    - name: "education"
    - name: "skills"


markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn 
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
      
