baseURL: 'http://qurist.github.io'
languageCode: 'en-us'
title: 'Aniruddha Bapat'
theme: 'PaperMod'

taxonomies:
  tag: tags

menu:
  main:
    - name: Curriculum Vitae
      url: curriculum-vitae/
      weight: 1  
    - name: Papers
      url: papers/
      weight: 2
    - name: Tags
      url: tags/
      weight: 2
      
params:
  # label:
  #   text: "Aniruddha Bapat"
  #   icon: /favicon-a.png
  #   iconHeight: 24

  math: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  hideFooter: True
  ShowToc: true

  cover:
    hiddenInList: true
    hiddenInSingle: true

  profileMode:
    enabled: true
    title: Aniruddha Bapat
    subtitle: |
        I am a physicist who has worked primarily in the field of [quantum computation](/tags/quantum-computation/), 
        with some experience in [computational biophysics](/papers/mastersthesis) and quantitative finance. 
        I have a broad range of interests with similar underlying themes I find appealing, such as computation, probability theory, and complex systems.<br>

        Until January 2024, I was a researcher at the high-frequency trading firm [Optiver](https://optiver.com). 
        Before that, I worked as a postdoc in quantum computing at the [Lawrence Berkeley National Laboratory](http://www.lbl.gov "lbl.gov"). 
        And before that, I was a Lanczos Graduate Fellow (2016-2018) with the Joint Center for Quantum Information and Computer Science ([QuICS](https://quics.umd.edu)) at the University of Maryland, where I received my [PhD](/papers/phdthesis) in 2021. 
        On this website you can find my [CV](/curriculum-vitae/) and a list of my [previous projects](/papers/).<br>
        
        ---
        
        Here are some of my interests outside of work:
        - I enjoy drinking (and brewing) coffee. My favorite drink is a cortado with about 4 grams of sugar.
        - My fiancée and I are avid foragers, and among the growing list of mushrooms
         we have found in the wild are such luminaries as the morel, the chanterelle, puffballs (giant and small), chicken of the woods, and *maitake* (also known as the hen of the woods). 
         We've spotted some interesting herbs too.
        - During the pandemic, I was gifted a homebrewing kit for my birthday by my cousin Devashish, and what started as a fun experiment soon broke out into a pretty serious brewing hobby. 
        We made a Belgian-style tripel, IPAs, and several other styles of beer, some of which were of our own invention. 
        One time we made a batch so dubious that several bottles exploded during the fermentation process and had to be safely de-pressurized in our backyard before they caused any further havoc. 
        Luckily, no one was harmed.
        - I play chess. Huge fan of the Botez gambit. 
    imageUrl: "/profile_pic_2024.jpeg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Aniruddha Bapat

  assets:
    disableHLJS: true
    disableScrollBarStyle: true

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/qurist"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/aniruddhabapat/"
    - name: "googlescholar"
      url: "https://scholar.google.com/citations?user=D5qEcgYAAAAJ&hl=en"
    - name: "email"
      url: "mailto:ani1729@gmail.com"
    - name: "CV"
      url: "/cv_aniruddhabapat.pdf"

  cvItems: 
    - name: "work-experience"
    - name: "education"
    - name: "skills"


markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn 
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
      
